### ISSUE TITLE
[Bug] 英文标题长度超过两行后换行有问题

### ISSUE THREAD

**Issue by Evyde** [Sakura-shem/JLUThesis#1]
首先感谢您的模版！膜拜大佬。

<img width="274" alt="image" src="https://github.com/Sakura-shem/JLUThesis/assets/9302540/fedcacbd-2a5b-4546-a536-1dad9e8377ea">

如图，在英文标题过长后会出现换行间距不够的问题，可能中文标题也存在类似问题。

请问有什么好的解决方法？

**Comment by jlshen025** [comment]
JLUThesis.cls 文件已经更新，下载最新版本的文件然后替换就可以解决这个问题了。
![image](https://github.com/Sakura-shem/JLUThesis/assets/78149191/0650ddcb-fe28-43d4-a321-ee5c08998792)

感谢提出 issue \^o^/
