### ISSUE TITLE
[Bug] 摘要超过一页时，页首会显示横线

### ISSUE THREAD

**Issue by Evyde** [Sakura-shem/JLUThesis#2]
抱歉大佬，再次叨扰。

<img width="669" alt="image" src="https://github.com/Sakura-shem/JLUThesis/assets/9302540/38a0d79c-9d62-4a0a-99c9-cd959bd0bebe">

如图，目前只尝试了英文Abstract部分，第二页页首没有横线。

**Comment by Evyde** [comment]
顺便，大佬是否可以给一个私人联系方式？

**Comment by jlshen025** [comment]
JLUThesis.cls 更新了，下载然后覆盖你那边的就可以了。main.tex 里面目录及之前的部分也有变动，对应改下调用方式就好了。 
![image](https://github.com/Sakura-shem/JLUThesis/assets/78149191/1ece7f1f-8a9b-451b-9a93-c18dd1fdd6e9)

感谢提出的 issus👍

> 顺便，大佬是否可以给一个私人联系方式？

telegram 私聊你了
