### ISSUE TITLE
hello bro

### ISSUE THREAD

**Issue by Astrorix** [Sakura-shem/JLUThesis#3]
## However，the format of the abstract is a little different from the one below.(Maybe I wrong
![image](https://github.com/Sakura-shem/JLUThesis/assets/66193058/175b1d2c-4793-45e2-a906-bbf816b71e78)
![image](https://github.com/Sakura-shem/JLUThesis/assets/66193058/a567caa1-6b7b-4d50-b43d-ad9bf5870e9a)

## Thanks to your work one more time！！

**Comment by jlshen025** [comment]
It seems that different majors template details are still different, I will try to adapt to different templates or you can try to modify based on my file.

**Comment by Astrorix** [comment]
[通信工程学院本科毕业论文（设计）撰写模板及装订要求(1).docx](https://github.com/Sakura-shem/JLUThesis/files/11562388/1.docx)

> I refer to this one. (×

**Comment by jlshen025** [comment]
Could you please tell me exactly which part you want to change, such as the font size of the “摘要”？
So that I can implement the style that you need.

**Comment by WannXing** [comment]
> 

emmm for example
the header of c/eabstract，i can`t find the way to modify
