### ISSUE TITLE
[Feature Request]图表名问题

### ISSUE THREAD

**Issue by Evyde** [Sakura-shem/JLUThesis#4]
原有图表序号直接按全文所有图片数进行编号，如图：
<img width="116" alt="image" src="https://github.com/Sakura-shem/JLUThesis/assets/9302540/d4424f49-aef1-42fc-92c2-0248297b1504">
似乎理应按照：
```text
图<章节号>-<章节内图号>[空格]<标题>
```
进行编号。

解决方案：
> 在`JLUThesis.cls`中加入：
> ```tex
> \RequirePackage{caption}
> \RequirePackage{subcaption}
> \renewcommand {\thetable} {\thechapter{}-\arabic{table}} 
> \renewcommand {\thefigure} {\thechapter{}-\arabic{figure}}
> \captionsetup{labelformat=default,labelsep=space} %去除冒号
> ```
> 且删除原有`% 图表编号 -- 全局`部分即可。

解决方案参考自：[Latex自定义设置 | Hummer's Blog](https://moeext.github.io/2019/05/14/latex-notes/)

**Comment by jlshen025** [comment]
图<章节号>-<章节内图号>[空格]<标题>

这个格式不是我们用的，我后面会把你写的这个样式加到 cls 文件里面，然后在 readme 里面更新对应用法的。
感谢 \^o^/

**Comment by jlshen025** [comment]
最新的版本已经支持多种样式的选择了，参考 readme 在 .cfg 文件中进行对应的选择就可以了。

**Comment by Evyde** [comment]
> 

好快！感谢！
